name: CI Pipeline

on:
  push:
    branches:
      - main
      - aula03

  pull_request:

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          pip install uv

      - name: Install Dependencies
        run: |
          uv pip install --system pytest
          uv pip install --system black

      - name: Check Code Formatting
        run: |
          black --check .

      - name: Run Tests
        run: |
          pytest